.Event delegation
****
Event delegation is a technique that makes use of bubbling in DOM events both as a form of code organization and to reduce memory usage, in situations where a large number of elements need to respond to an event in the same way.
Instead of attaching event listeners to each individual element, we attach a single listener to a shared parent element.
The parent listener determines which element the event arrived through.

The following is how event delegation would be usually implemented:

.With event delegation
[source,js]
----
ul.addEventListener('click', e => {
	const li = e.target.closest('li');
	if (!li) return;

	doThingWith(li);
});
----

whereas the alternative would be:

.Without event delegation
[source,js]
----
ul.querySelector('li').forEach(li => {
  li.addEventListener('click', e => {
    doThingWith(li);
  });
});
----

.Benefits of event delegation
* If elements are dynamically added, there is no need to add the event listener onto them (this usually requires extracting the listener to a named function, and code repeated in every place where events are added).
Event delegation can simplify code quite a lot.
* Having only one event listener reduces memory use.
* When code is inline in HTML, event delegation protects us from repetition.

.Drawbacks of event delegation
* The listener will execute for every click in a subtree (or other event type) when not all may be relevant.
* The listener will stay around even if no relevant elements remain.
****
