
= Effective HTML
:chapter: 03
:url: ./effective-html/

WARNING: This chapter is a work in progress.

If you're here, you can probably write some HTML.
The web is the #1 hypermedia system after all, the one this book will spend the most time with,
and HTML is its format.

As with every aspect of the web, it has been exapted and reinterpreted by web developers in myriad ways.
Is it a document format?
Is it for applications?
Is it a rendering system?
Is it (gasp!) a programming language?
These are the contenders in the Eternal Debate of the web development world,
and none will ever win because none of them are right.

[quote, Roy Fielding, https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718]
____
When I say hypertext, I mean the simultaneous presentation of information and controls such that the information becomes the affordance through which the user (or automaton) obtains choices and selects actions.
____

HTML, like all hypermedia, blurs the distinction between the information being accessed and the application used to access it. HTML is for documents, insofar as you're willing to adopt a broad definition of "`document`" -- and it is for applications, ones that are interwoven with the data they process.

HTML is a hypermedium.

An HTML file is not a program that produces a human-readable document.
It _is_ the document.

Unfortunately, HTML isn't often discussed in its own right.
As a result, its development in terms of hypermedia controls has stagnated.

This chapter looks at HTML as something worth studying in its own right, even in this day and age.
It covers our best practices for writing/generating HTML,
and why HTML is something far cooler than a programming language.


== The state of affairs

Have you noticed that a lot of websites are bad?

 - Pages are bloated with `<div>` soup, and stylesheets are big as a result of trying to select elements in that mess. The result is slow loading times.footnote:[https://almanac.httparchive.org/en/2020/markup] Other than `<div>` being the most common element, the HTTP Archive Web Almanac found that 0.06% of pages surveyed in 2020 contained the nonexistent `<h7>` element. 0.0015% used `<h8>`.
 - Websites, including websites containing public data or results of publicly-funded research, are impossible to scrape programmatically.
 - So-called MVPs (minimum viable product) are released in open beta while being completely unusable by vast swathes of people -- UX not just buggy, but nonexistent.footnote:[https://adrianroselli.com/2022/11/accessibility-gaps-in-mvps.html] Is an inaccessible product "`viable`"?
 - Search engines have a hard time extracting useful information from a page, and rank that page lower as a result. 

There are several disparate reasons for these issues, but the neglect of HTML is a significant one.

The way most of us write HTML (and likely the way many of us learned it) is a very tight feedback loop:
we write something, _Alt-Tab_ to the browser to see if it works, and go back to edit.
It's an amazingly fast and enjoyable way to build, but the way it's often practiced has a significant flaw:
_If it looks right, it gets shipped._
The developer is focusing almost exclusively to their own UI needs.
Any other way of using a website becomes an afterthought.

We should first note that, if you care about machine readability, or human readability, or page weight,
what you should do is **test**.
Test manually.
Test automatically.
Test with screenreaders, test with a keyboard, test on different browsers and hardware, run linters (while coding and/or in CI).

So where does HTML and the s-word come in?

Easy. Writing good, spec-compliant HTML lets browsers do a bunch of work for you. Furthermore, even when they don't, it makes it easier to write scripts that do. Fewer issues will be found during testing and you can release faster. When issues do come up, you can often fix them more easily by rewriting semantic HTML as opposed to heaping JavaScript and ARIA attributes over everything.

Good HTML will not absolve you from doing your job, but it will make it easier.


== HTML practices


=== Stay close to the output

Web frameworks, particularly SPA frameworksfootnote:[
This also applies to frameworks like Next and Remix that use SPA technologies like React to render static HTML.],
can have a tall tower of abstraction between the code the developer writes and the generated markup.
While these abstractions can allow developers to create richer UI or work faster,
their pervasiveness means that they can lose sight of the actual HTML (and JavaScript) being sent to clients.
Without diligent testing, this leads to poor semantics, inaccessibility, bloat and soup.

One popular concept found in many frameworks is *components*.
Components encapsulate a section of a page along with its dynamic behavior.
While encapsulating behavior is a good way to organize code,
they also separate elements from their surreounding context,
which can lead to wrong or insufficiently specific semantics,
and conceal the number of elements within,
which can lead to bloat and soup.
In chapter:[Client Side Scripting], we'll look at alternative tools and architectures that can be used to avoid these shortcomings.

Generally, lower level solutions will let you create better HTML.
Instead of reaching for frameworks, consider using less abstract options:

* Could you get away with a static hand-written HTML file?
* If not, could you use a simple template?

It can also be a good idea to check the resulting HTML, especially when evaluating a new tool or library.


=== Refer frequently to the spec

[quote,Confucius]
The beginning of wisdom is to call things by their right names.

The best resource for learning about HTML is the HTML specification.
The current specification lives on link:https://html.spec.whatwg.org/multipage[].footnote:[
The single-page version is too slow to load and render on most computers.]

Section 4 features a list of all tags in HTML.
It includes what tags mean, where they can occur, and what they are allowed to contain.
It even tells you when you're allowed to leave out closing tags!

[source,html]
----
<!doctype html>
This is a valid HTML document.
----

This chapter in particular is not only a great piece of reference material, but also a good read in general.
Reading it through (skipping over the implementation details) will give you a sense of how HTML is intended to be written.

.You get what you pay for
****
The close relationship between the content and the markup means that good HTML is actually quite expensive.
Most sites have a CMS between the authors, who are rarely familiar with HTML and _very_ rarely want to think about it,
and the developers, who need to develop a generic system able to handle any content that's thrown at it.
As a result, having markup tailored to content, which is often necessary for advanced HTML, is rarely feasible.
Furthermore, for internationalized sites, content in different languages being injected into the same elements can degrade markup quality as stylistic conventions differ between languages.
Dishearteningly, but understandably, it's an expense few organizations can spare.

Thus, we don't demand that every site contains the "most semantic" HTML.
What's most important is to avoid _wrong_ HTML -- it can be better to fall back on a more generic element than to be precisely incorrect.
Most of the defects caused by _inadequate_ HTML can be caught through testing.

If you have the resources, however, putting more care in your HTML will produce a more polished site.
Much like style guides, well-written semantic HTML gives an air of quality and prestige to a document, even when few people notice it.
It can also make your HTML easier to maintain.
****


=== Don't make soup

While programming code turns into spaghetti when it's not well organized,

==== HTML5 soup

A set of elements introduced with HTML5 have become a symbol of semantic markup:

 - section
 - article
 - nav
 - header
 - footer

Don't write HTML with the mindset of
"`The more of these elements there are, the more semantic it is.`"
Otherwise, the results might look somewhat like this:

.HTMHell, [.cite]##10 <section> is no replacement for <div>#, https://www.htmhell.dev/10-section-is-no-replacement-for-div/
[source,html]
----
<section id="page-top">
  <section data-section-id="page-top" style="display: none;"></section>
</section>
<main>
  <section id="main-content">
    <header id="main-header">
      <h1>...</h1>
      <section class="container-fluid">
        <section class="row">
          <article class="content col-sm-12">
            <section class="content-inner">
              <div class="content__body">
                <article class="slider">
                  <section class="slide"> … </section>
                </article>
              </div>
            </section>
          </article>
        </section>
      </section>
    </header>
  </section>
</main>
----

Sometimes, `<div>` really is fine.


==== Div soup

However, while you shouldn't abuse advanced HTML, you shouldn't restrict yourself either.
Instead, learn the meaning of every tag and consider each another tool in your tool chest.
(With the 113 elements currently defined in the spec, it's more of a tool shed).

// Master the full range of HTML elements
// i, cite, dfn, address etc.
// Don't limit yourself to Markdown
// WAR IS PEACE
// IGNORANCE IS STRENGTH
// THE <STRONG> TAG REPRESENTS STRONG EMPHASIS

.The S word
****
[quote, _Mean Girls_ (2004)]
Gretchen, stop trying to make fetch happen! It's not going to happen!

In natural language, a word can only have a certain meaning if some group of people know it to have that meaning.
You could define your own words and use them, the aforementioned Ted Nelson and company really liked to, but it's difficult.

[quote, , Xanadu Hypertext Documents]
The index space used by the granfilade is I-stream tumbler space. The wid of a granfilade crum is a tumbler specifying the span of I-space beneath the crum (i.e., the distance, in tumbler space, from the first to the last bottom crum descended from it). The widdative function is tumbler addition, therefore a crum’s wid is simply the tumbler sum of its children’s wids. Bottom crums have an implicit wid of 0.0.0.0.1 (i.e., spanning no nodes, no accounts, no orgls, no V-spaces and spanning a single atom). Granfilade disps are tumbler offsets in I-space from the parent crum.

As this applies to computer languages too, any hypermedia format which lets documents define their own elements is an infinite universe of "`fetch`"-es to make happen.
This was a massive blind spot in the Semantic Web, which dominated hypermedia discourse for years:
its semantics attempted to replace natural language.

The semantic web is considered a failure, and the __schematamania__ is over.
Instead, when we talk about semantics, we refer to the simple act of using elements in accordance with their agreed-upon meaning.
Our semantics do

Instead of being extensible through schemas or namespaces, or whatever DTDs are, HTML is extended in two ways:

 - **Ad-hoc extensibility.** HTML is a fault-tolerant language, choosing to ignore things it doesn't recognize instead of throwing errors.
   This means you can use unspecified attributes.
   htmx relies on this heavily.
   If extensions see common acceptance, they might even be incorporated into specifications! (We can dream.)
 - **Specified extension points.** Things like classes, `<meta>` tags, custom elements and `data-` attributes are made for custom data.
   They can be used to build meta-languages embedded in HTML.

This might seem like a downgrade, and an anxiety-inducing one at that.
Think of the name collisions!
Indeed, it has some significant compromises, but it also correctly acknowledges that defining custom semantics without prior agreement between all parties is a fiction.
A flexible format --not an infinity of namespaces with URLs pointing to nothing --is "`software design on the scale of decades`".

Let's be real, after all --out of all the sites using "`Open Graph`" tags, how many use the appropriate `prefix` attribute? How many of their developers even know the `prefix` attribute exists?
****


=== Focus on people

The purpose of writing good HTML is not to please the specification deities.
It's to make good websites.
The spec is a good starting point when deciding how to mark something up,
but when implementations don't conform,
don't throw up your hands because you did what was specified.

It is of course frustrating when browsers and other tools misbehave.
It helps with the frustration is to recognize that hypermedia exchanges are not machine-to-machine communication.
An HTML file is not a program that produces a human-readable document.
It _is_ the document.
So, instead of banging your head against a wall, focus on people, not the tools they use.

Don't write HTML for browsers. or assistive tools, or validators.
HTML is not _for_ them.
HTML is for humans.


=== ARIA is easy -- as long as you stick to the basics

// Stick to the patterns

// Don't compromise UX just to avoid JS

// Consider using off the shelf components

// WAI has a very friendly webpage


=== Machine-readable HTML

==== Data attributes

// TODO to mark elements,to store state


==== Microformats

<https://microformats.org/>


=== Custom elements

// TODO get on a soapbox about custom elements, why they're good and disappointing


== Relearning HTML

* HTML specification: https://html.spec.whatwg.org/multipage
* TODO link resources on alt text.
