
= Effective HTML
:chapter: 03
:url: ./effective-html/

WARNING: This chapter is a work in progress.

[quote, Marshall McLuhan]
The medium is the message.

If you're here, you can probably write some HTML.
The web is the #1 hypermedia system after all, the one this book will spend the most time with,
and HTML is its format.

As with every aspect of the web, it has been exapted and reinterpreted by web developers in myriad ways.
Is it a document format?
Is it for applications?
Is it a rendering system?
Is it (gasp!) a programming language?
These are the contenders in the Eternal Debate of the web development world,
and none will ever win because none of them are right.

[quote, Roy Fielding, https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718]
____
When I say hypertext, I mean the simultaneous presentation of information and controls such that the information becomes the affordance through which the user (or automaton) obtains choices and selects actions.
____

HTML, like all hypermedia, blurs the distinction between the information being accessed and the application used to access it. HTML is for documents, insofar as you're willing to adopt a broad definition of "`document`" -- and it is for applications, ones that are interwoven with the data they process.

HTML is a hypermedium.

An HTML file is not a program that produces a human-readable document.
It _is_ the document.

Unfortunately, HTML isn't often discussed in its own right.
As a result, its development in terms of hypermedia controls has stagnated.

This chapter looks at HTML as something worth studying in its own right, even in this day and age.
It covers our best practices for writing/generating HTML,
and why HTML is something far cooler than a programming language.
It won't be an HTML tutorial, as that would take a whole other book, but it can accompany you in your HTML re-learning journey.


== Why relearn HTML?

Have you noticed that a lot of websites are bad?

 - Pages are bloated with `<div>` soup, and stylesheets are big as a result of trying to select elements in that mess. The result is slow loading times.footnote:[https://almanac.httparchive.org/en/2020/markup] Other than `<div>` being the most common element, the HTTP Archive Web Almanac found that 0.06% of pages surveyed in 2020 contained the nonexistent `<h7>` element. 0.0015% used `<h8>`.
 - So-called MVPs (minimum viable product) are released in open beta while being completely unusable by vast swathes of people -- UX not just buggy, but nonexistent.footnote:[https://adrianroselli.com/2022/11/accessibility-gaps-in-mvps.html] Is an inaccessible product "`viable`"?
 - Websites, including websites containing public data or results of publicly-funded research, are impossible to scrape programmatically.
 - Search engines have a hard time extracting useful information from a page, and rank that page lower as a result. 

In the rest of the chapter, we'll look at these issues in more detail and see how effective HTML can help us develop better websites.
However, we should first note that HTML is not a panacea.
If you care about machine readability, or human readability, or page weight, the most important thing to do is **testing**.
Test manually.
Test automatically.
Test with screenreaders, test with a keyboard, test on different browsers and hardware, run linters (while coding and/or in CI).

So where does HTML and the s-word come in?

Easy. Writing good, spec-compliant HTML lets browsers do a bunch of work for you. Furthermore, even when they don't, it makes it easier to write scripts that do. Fewer issues will be found during testing and you can release faster. When issues do come up, you can often fix them more easily by rewriting semantic HTML as opposed to heaping JavaScript and ARIA attributes over everything.

Knowing HTML well might not absolve you from doing your job, but it makes it a lot easier.

"`But I already know HTML well.`"
Maybe you do.
But many people underestimate how sophisticated HTML is.
Indeed, it's very easy (and sometimes acceptable) to produce mediocre HTML that _seems to_ work,
and many websites settle with _seeming to_ work.
But better websites are possible, and anyone can learn HTML to the level of making websites that _actually_ work.


== `<div>` soup

While programming code is described as spaghetti when it's not well organized,
the food of choice for messy markup is soupfootnote:[hence BeautifulSoup, the web scraping library.].

HTML can turn into soup in a variety of ways,
usually due to a disregard for or misunderstanding of semantics
or due to an excess of layers between the developer and the HTML.

The best-known kind of messy HTML is `<div>` soup.
When developers fall back on the generic `<div>` and `<span>` elements instead of more meaningful tags,
we either degrade the quality of our websites or create more work for ourselves -- probably both.

For example, instead of adding a button using the dedicated `<button>` element,
a `<div>` element might have a `click` event listener added to it.

[source,html]
----
<div class="bg-accent padding-4 rounded-2" onclick="doStuff()">Do stuff</div>
----

Why might a developer do this, when the `<button>` element is right there?
There could be a few reasons:

 * *Styling.* The `<button>` element might have been harder to style.
 * *Confusion.* The button might have some other interactive features, which could lead to the developer not realizing it was a button.
 * *Apathy.* The developer doesn't care, and uses `<div>` except when he has to.

It's absolutely possible to implement this button, and indeed most kinds of UI, using nothing but `<div>`.
However, it makes the job harder.

There are two main issues with this button:

* It's not focusable -- the Tab key won't get you to it.
* There's no way for assistive tools to tell that it's a button.

Let's fix that:

[source,html]
----
<div class="bg-accent padding-4 rounded-2"
  role="button" <1>
  tabindex="0" <2>
  onclick="doStuff()">Do stuff</div>
----
<1> Expose this element as a button.
<2> Make this element focusable.

Of course, these are both easy fixes but they're things you have to _remember_.
It's not obvious from the HTML source that this is a button,
making the source harder to read and the absence of these attributes harder to spot.
Furthermore, even if you always remember to add the correct attributes and JavaScript
-- and yes, if you're making almost anything more complex than a button, you will need a lot of JavaScript --
you've made your HTML less readable for little reason.
The source code of pages with div soup is difficult to edit and debug.

We often _don't_ remember these types of UX and accessibility issues.
[.dfn]_F5-Driven Development_ is the way most of us write HTML:
write something, _Alt-Tab_ to the browser to see if it works, and go back to edit.
It's a fast and enjoyable way to build things,
but it means that during most of development,
developers are biased towards their own UI needs,
and users (who might use websites differently) become an afterthought.
However, if we use HTML effectively, we can catch many of these issues before they ever occur, even before testing.

Given all this, why are so many developers writing div soup?
There is a tendency to understate the sophistication of HTML.

Instead, learn the meaning of every tag and consider each another tool in your tool chest.
(With the 113 elements currently defined in the spec, it's more of a tool shed).

[.dfn]_Markdown soup_ is the lesser known sibling of `<div>` soup.
This is the result of web developers limiting themselves to the set of elements that the Markdown language provides shorthand for,
even when these elements are incorrect.
Consider the following example of an IEEE-style citation:

[source,markdown]
----
[1] C.H. Gross, A. Stepinski, and D. Akşimşek, <1>
_Hypermedia Systems_, <2>
Bozeman, MT, USA: Big Sky Software.
Available: <https://hypermedia.systems/>
----
<1> The reference number is written in brackets.
<2> Underscores around the book title creates an <em> element.

Here, <em> is used because it's the only Markdown element that is presented in italics by default.
This indicates that the book title is being stressed, but the purpose is to mark it as the title of a work.
HTML has the `<cite>` element that's intended for this exact purpose.

Furthermore, even though this is a numbered list perfect for the `<ol>` element, which Markdown supports, plain text is used for the reference numbers instead.
Why could this be?
The IEEE citation style requires that these numbers are presented in square brackets.
This could be achieved on an `<ol>` with CSS,
but Markdown doesn't have a way to add a class to elements meaning the square brackets would apply to all ordered lists.

[.info]
****
We call `<ol>` and `<ul>` "ordered" and "unordered" lists. Both are actually ordered, however, and the difference is whether the place of a particular element is significant. For instance, instructions should usually be marked up with `<ol>` since it may contain references like "Repeat steps 3 to 5". If we were using a style like APA in our reference list, where citations are not referenced by number, we would use an `<ul>`.
****

Don't shy away from using embedded HTML in Markdown.
For larger sites, also consider Markdown extensions.

[source,markdown]
----
{.ieee-reference-list} <1>
1. C.H. Gross, A. Stepinski, and D. Akşimşek, <2>
   <cite>Hypermedia Systems</cite>, <3>
   Bozeman, MT, USA: Big Sky Software.
   Available: <https://hypermedia.systems/>
----
<1> Many Markdown dialects let us add ids, classes and attributes using curly braces.
<2> We can now use the <ol> element.
<3> We use `<cite>` to mark the title of the work being cited (not the whole citation!)

You can also use custom processors to produce extra-detailed HTML instead of writing it by hand:

[source,markdown]
----
{% reference_list %} <1>
[hypers2023]: <2>
C.H. Gross, A. Stepinski, and D. Akşimşek, _Hypermedia Systems_,
Bozeman, MT, USA: Big Sky Software, 2023.
Available: <https://hypermedia.systems/>
{% end %}
----
<1> `reference_list` is a macro that will transform the plain text to semantic HTML.
<2> A processor can also resolve identifiers, so we don't have to manually keep the reference list in order and the in-text citations in sync.


=== Remedy: Stay close to the output

[quote, Manuel Matuzović, 'https://www.matuzo.at/blog/2023/single-page-applications-criticism[Why I\'m not the biggest fan of Single Page Applications]']
The fact that the HTML document is something that you barely touch, because everything you need in there will be injected via JavaScript, puts the document and the page structure out of focus.

In order to avoid `<div>` soup (or Markdown soup, sub-par semantics in general), you need to constantly be aware what kind of markup you're producing and be able to change it.

Web frameworks, particularly SPA frameworksfootnote:[
This also applies to frameworks like Next and Remix that use SPA technologies like React to render static HTML.],
can have a tall tower of abstraction between the code the developer writes and the generated markup.
While these abstractions can allow developers to create richer UI or work faster,
their pervasiveness means that they can lose sight of the actual HTML (and JavaScript) being sent to clients.
Without diligent testing, this leads to poor semantics, inaccessibility, and bloat.

For example, a popular concept found in many frameworks is *components*.
Components encapsulate a section of a page along with its dynamic behavior.
While encapsulating behavior is a good way to organize code,
they also separate elements from their surrounding context,
which can lead to wrong or inadequate semantics,
and conceal the number of elements within.
The result is what one might call [.dfn]_component soup_,
where information is hidden in component state,
rather than being present in the HTML, which is now incomprehensible due to missing context.
In our Client Side Scripting chapter, we'll look at alternatives to component-based frameworks that can be used to avoid these shortcomings.

To be abundantly clear, components aren't the cause of all div soup.
Not even most of it.
The root cause is the fact that HTML is falsely believed to be very simple,
and as a result, developers and organizations don't invest in learning and applying HTML skills.
However, don't reach for components for reuse without considering other options.
Lower-level mechanisms usually (allow you to) produce better HTML.

Components, when used well, can actually _improve_ the clarity of your HTML.
To decide if a component is appropriate for your use case, a good rule of thumb is to ask:
"`Could this reasonably be a built-in HTML element?`"
For example, a code editor is a good candidate,
since HTML already has `<textarea>` and `contenteditable` elements.
In addition, a fully-featured code editor will have many child elements that won't provide much information anyway.
We can use features like
link:https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM[Shadow DOM]
to encapsulate these elementsfootnote:[
Beware that Shadow DOM is a newer web platform feature that's still in development at the time of writing.
In particular, there are some accessibility issues that may occur when elements inside and outside the shadow root interact.].
We can create a
link:https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements[custom element],
`<code-area>`, that we can drop into our page whenever we want.
See how we're _extending_ HTML, rather than abstracting it away.

.Web Components
****
// TODO get on a soapbox about custom elements, why they're good and disappointing
Web Components is the collective name of a few standards;
Custom Elements and Shadow DOM, and `<template>` and `<slot>`.

All of these standards bring useful capabilities to the table.
`<template>` elements remove their contents from the document, while still parsing them as HTML (unlike comments) and making them accessible to JavaScript.
Custom Elements let us initialize and tear down behaviors when elements are added or removed, which would previously require manual work or MutationObservers.
Shadow DOM lets us encapsulate elements, leaving the "light" (non-shadow) DOM clean and semantic.

However, trying to actually reap these benefits is often frustrating.
Some of these are simply growing pains of new standards
(like the many accessibility problems of Shadow DOM)
that are actively being worked on.
Others are the result of Web Components trying to be too many things at the same time:

 * An extension mechanism for HTML. To this end, each custom element is a tag we add to the language.
 * A lifecycle mechanism for behaviors. Methods like `createdCallback`, `connectedCallback`, etc. allow behavior to be added to elements without needing to be manually invoked when those elements are added.
 * A unit of encapsulation. Shadow DOM insulates elements from their surroundings.

The result is that if you want any one of these things,
the others come along for the ride.
If you want to attach some behaviors to some elements using lifecycle callbacks,
you need to create a new tag,
which means you can't have multiple behaviors on one element,
and you isolate elements you add from elements already in the page,
which is a problem if they need to have ARIA relationships.
****

== HTML5 soup

Yeah! Down with `<div>`! It's time to use *Semantic HTML!*

Carefully.

A particular set of elements introduced with HTML5 have become a symbol of semantic markup:
`<section>`, `<article>`, `<nav>`, `<header>`, `<footer>`, `<figure>` and more.
To make HTML5 soup, convince yourself that the more of these elements there are in a page, the more semantic it is.
Don't change your development habits in any other way and you have HTML5 soup:

.HTMHell, [.cite]##10 <section> is no replacement for <div>#, https://www.htmhell.dev/10-section-is-no-replacement-for-div/
[source,html]
----
<section id="page-top">
  <section data-section-id="page-top" style="display: none;"></section>
</section>
<main>
  <section id="main-content">
    <header id="main-header">
      <h1>...</h1>
      <section class="container-fluid">
        <section class="row">
          <article class="content col-sm-12">
            <section class="content-inner">
              <div class="content__body">
                <article class="slider">
                  <section class="slide"> … </section>
                </article>
              </div>
            </section>
          </article>
        </section>
      </section>
    </header>
  </section>
</main>
----

Most HTML isn't this much of a mess,
but `<section>` and `<article>` in particular are often used as a drop-in replacement `<div>` without considering its purpose.
If you're experiencing HTML5 soup, there are two remedies:

* Check the spec. Don't try to use advanced HTML without learning it.
* Don't try to be specific with your semantics when you can't or don't need to.
  Sometimes, `<div>` really is fine.


=== Remedy: Keep the spec on hand

[quote,Confucius]
The beginning of wisdom is to call things by their right names.

The most authoritative (though not necessarily best) resource for learning about HTML is the HTML specification.
The current specification lives on link:https://html.spec.whatwg.org/multipage[].footnote:[
The single-page version is too slow to load and render on most computers. 
There's also a developers' edition at /dev, though there's little difference between the two.]
There's no need to rely on hearsay to keep up with developments in HTML.

Section 4 features a list of all available elements.
It includes what tags mean, where they can occur, and what they are allowed to contain.
It even tells you when you're allowed to leave out closing tags!

[source,html]
----
<!doctype html>
<html lang=en>
This is a valid HTML document.
----

[.info]
****
The `<html>` tags can be omitted but it's bad practice to leave out the opening tag since it holds the  `lang` attribute which specifies the language of the document.
****

This chapter in particular is a great piece of reference material and an useful read in general.
Reading it through (skipping over the implementation details, like the several pages of algorithms)
will give you a sense of how HTML is intended to be written.


=== Remedy: Know your budget

The close relationship between the content and the markup means that
good HTML is actually quite labor-intensive, often across a whole organization.
Most sites have a separation between the authors,
who are rarely familiar with HTML and _very_ rarely want to think about it,
and the developers, who need to develop a generic system able to handle any content that's thrown at it --
this separation usually taking the form of a CMS.
As a result, having markup tailored to content, which is often necessary for advanced HTML, is rarely feasible.
Furthermore, for internationalized sites, content in different languages being injected into the same elements can degrade markup quality as stylistic conventions differ between languages.
Dishearteningly, but understandably, it's an expense few organizations can spare.

Thus, we don't demand that every site contains the "most semantic" HTML.
What's most important is to avoid _wrong_ HTML -- it can be better to fall back on a more generic element than to be precisely incorrect.
The kinds of defects caused by _inadequate_ HTML can usually be caught through testing.

If you have the resources, however, putting more care in your HTML will produce a more polished site.
Much like style guides, well-written semantic HTML gives an air of quality and prestige to a document, even if few notice it.
When it comes to HTML, you get what you pay for.


== The S word

[quote, '_Mean Girls_ (2004)']
Gretchen, stop trying to make fetch happen! It's not going to happen!

In natural language, a word can only have a certain meaning if some group of people know it to have that meaning.
Whereas in programming, we are used to defining functions and variables, creating names for them at a break-neck pace.
This is possible because the computer doesn't need to understand the names of functions to execute them.
However, hypermedia formats are not programming languages.
The names in HTML are not _identifiers_ for behavior, but _words_ with well-understood meanings.
Any hypermedia format which lets documents define their own elements is an infinite universe of "`fetch`"-es to make happen.

This was a massive blind spot in the Semantic Web, which dominated hypermedia discourse for years:
its semantics attempted to replace natural language, but also be pluggable with custom namespaces.

The semantic web is considered a failure, and Schematamania will soon be over.
Instead, when we talk about semantics, we refer to simply using elements in accordance with their agreed-upon meaning to augment documents for humans.
Our semantics don't try to replace natural language, they are dependent on natural language and natural understanding.

Instead of being extensible through schemas or namespaces, or whatever DTDs are, HTML is extended in two ways:

 - **Ad-hoc extensibility.** HTML is a fault-tolerant language, choosing to ignore things it doesn't recognize instead of throwing errors.
   This means you can use unspecified attributes.
   htmx relies on this heavily.
   If extensions see common acceptance, they might even be incorporated into specifications! (We can dream.)
 - **Specified extension points.** Things like classes, `<meta>` tags, custom elements and `data-` attributes are made for custom data.
   They can be used to build meta-languages embedded in HTML.

This might seem like a downgrade, and an anxiety-inducing one at that.
Think of the name collisions!
Indeed, it has some significant compromises, but it also correctly acknowledges that defining custom semantics without prior agreement between all parties is a fiction.
A flexible format -- not an infinity of namespaces with URLs pointing to nothing -- is "`software design on the scale of decades`".

Let's be real, after all -- out of all the sites using "`Open Graph`" tags, how many use the appropriate `prefix` attribute? How many of their developers even know the `prefix` attribute exists?


== The A word

So far throughout this chapter, we've gestured at potential accessibility benefits to be had from effective HTML.

[quote, Manuel Matuzović, 'https://alistapart.com/article/my-accessibility-journey-what-ive-learned-so-far/[My Accessibility Journey: What I’ve Learned So Far]']
(Re)learning HTML and using it consciously prevents and fixes many accessibility issues.

It's true that all else being equal, an app that makes full use of HTML will be more accessible than one that is made of soup.
However, HTML is not a panacea.
Even the adage that HTML is "`accessible by default`" is misleading.

Problems often arise when we try to implement controls that aren't built into HTML.
Sometimes, JavaScript is necessary to implement a UI control in an accessible manner
(i.e. supporting all required keyboard interaction and presenting state to assistive tools).
Clever "tricks" to implement controls in only HTML/CSS are fun, but often not practical.
Take the following code, which uses radio buttons and CSS hacks to create something that resembles tabs:

[source,html]
----
<input type="radio" name="tabs" id="tab1" checked>
<label for="tab1">Tab 1</label> <1>
<input type="radio" name="tabs" id="tab2">
<label for="tab2">Tab 2</label>

<div class="tabpanel" id="tabpanel1">Tab 1 contents</div>
<div class="tabpanel" id="tabpanel2">Tab 2 contents</div>

<style>
  input[name="tabs"] { display: none; } <2>
  .tabpanel { display: none; }
  #tab1:checked ~ #tabpanel1 { display: block; } <3>
  #tab2:checked ~ #tabpanel2 { display: block; } <3>
</style>
----
<1> Each tab is an `<input>` and a `<label>`.
<2> Hide the radio buttons. We can actuate them by clicking the associated labels.
<3> A tabpanel will be visible when the associated tab is selected.

This code will "`work.`"
Clicking on the tabs will change the content displayed, and without a single line of JavaScript.
Unfortunately, tabs have requirements beyond clicking to change content.
This implementation has many missing features that will lead to user confusion and frustration, as well as some undesirable behaviors.
From the link:https://www.w3.org/WAI/ARIA/apg/patterns/tabs/[ARIA Authoring Practices Guide on tabs]:

* Keyboard interaction

** The tabs can't be focused with the Tab key. Because the radio buttons are hidden with `display: none`, they are removed from the focus order, and label elements are not focusable.

** "`[...] does not listen for Down Arrow or Up Arrow so those keys can provide their normal browser scrolling functions [...]`" 
   Radio buttons listen to these events (since they're usually presented vertically). Thankfully, right and left arrow keys also work.

* ARIA roles, states, and properties

** "`[The element that contains the tabs] has role `tablist`.`" 
   There is no such element in this implementation, as that would break the CSS.

** "`Each [tab] has role `tab` [...]`"
   The tab elements have role `label`. Furthermore, the elements they are labeling are hidden.

** "`Each element that contains the content panel for a `tab` has role `tabpanel`.`"
   No, though that could be added.

** "`Each [tab] has the property `aria-controls` referring to its associated tabpanel element.`"
   Nope.

** "`The active `tab` element has the state `aria-selected` set to `true` and all other `tab` elements have it set to `false`.`"
   Nope.

** "`Each element with role `tabpanel` has the property `aria-labelledby` referring to its associated `tab` element.`"
   No. The element that _is_ labelled by the tab element is a hidden radio button.

[.info]
****
`display: none;` in CSS is not purely cosmetic -- it removes elements from the accessibility tree and keyboard focus. If you want to hide an element visually without hiding it from assistive technology, you can use this utility class:

[source,css]
----
.vh {
	clip: rect(0 0 0 0);
	clip-path: inset(50%);
	block-size: 1px;
	inline-size: 1px;
	overflow: hidden;
	white-space: nowrap;
}
----

`vh` is short for "`visually hidden.`"This class uses multiple methods and workarounds to make sure no browser removes the element's function.
****

It turns out that fulfilling all of these requirements takes a lot of code. 
Some of the ARIA attributes can be added directly in HTML,
but they are repetitive
and others (like `aria-selected`) need to be set through JavaScript since they are dynamic.
The keyboard interactions can be error-prone too.
It's not impossible to make a good tab set implementation.
However, it's difficult to trust that a new implementation will work in all environments, since most of us have limited access to testing devices.
This is why it's often recommended to use established libraries for UI interactions instead of rolling your own.

Before adding a dependency, however, let's reconsider our design.
Does the information really need to be presented as tabs?
Sometimes the answer is yes
(we used dummy text in our code example, so we can't tell),
but if not, a sequence of details disclosures fulfills a very similar purpose.

[source,html]
----
<details><summary>Disclosure 1</summary>
  Disclosure 1 contents
</details>
<details><summary>Disclosure 2</summary>
  Disclosure 2 contents
</details>
----

Compromising UX just to avoid JavaScript is bad development.
At the same time, the possibilities and constraints of the platform should be considered while designing interfaces.
It might be possible to achieve an equal (or better!) quality of UX while allowing for a simpler and more robust implementation.
But when it's not, we shouldn't try to stuff every problem into an HTML box.

// Don't compromise UX just to avoid JS


=== Screen reader rage

{blank}// This section is supposed to be addressing the frustration many people experience trying to make accessible sites, how accessibility itself feels inaccessible to many developers.

The purpose of writing good HTML is not to please the specification deities.
It's to make good websites.
The spec is a good starting point when deciding how to mark something up,
but when implementations don't conform,
we shouldn't throw up our hands because we did what was specified.

It is of course frustrating when browsers and other tools misbehave.
It helps with the frustration is to recognize that hypermedia exchanges are not machine-to-machine communication.
An HTML file is not a program that produces a human-readable document.
It _is_ the document.
So, instead of banging your head against a wall, focus on people, not the tools they use.

Don't write HTML for browsers. or assistive tools, or validators.
HTML is not _for_ them.
HTML is for humans.


== Machine-readable HTML

Hypermedia systems perform best with human-operated clients.
However, machine-readable information can be embedded into HTML pages through a variety of extension mechanisms

=== Microformats

Here's how the reference list example from earlier could be marked up with the `h-cite` microformat:

[source,html]
----
<ol class="reference-list">
  <li class="h-cite" id="cite-hypers2023">
    <span class="p-author">C.&#8202;H. Gross</span>,
    <span class="p-author">A. Stepinski</span>,
    and <span class="p-author">D. Akşimşek</span>,
    <cite class="p-name">Hypermedia Systems</cite>,
    <span class="p-publisher h-card">
      <span class="p-adr h-adr">
        <span class="p-locality">Bozeman</span>,
        <span class="p-region">MT</span>,
        <span class="p-country-name">USA</span>
      </span>:
      <span class="p-name">Big Sky Software</span>
    </span>,
    <time class="dt-published">2023</time>.
    Available:
    <a class="u-url" href="https://hypermedia.systems/">
      https://hypermedia.systems/
    </a>
  </li>
</ol>
----

This can be parsed into a JSON-like structure, as follows:

[source,json]
----
{
  "type": ["h-cite"],
  "properties": {
    "author": ["C.\u200aH. Gross", "A. Stepinski", "D. Akşimşek"],
    "name": ["Hypermedia Systems"],
    "url": ["https://hypermedia.systems/"],
    "published": ["2023"],
    "publisher": [{
      "type": ["h-card"],
      "properties": {
        "name": ["Big Sky Software"],
        "adr": [{
          "type": ["h-adr"],
          "properties": {
            "locality": ["Bozeman"],
            "region": ["MT"],
            "country-name": ["USA"]
          }
        }]
      }
    }]
  }
}
----

<https://microformats.org/>


== Relearning HTML

If you're convinced that it's worth investing your time into HTML,
here are some useful resources to have at hand.

* Foundations
* HTML specification: https://html.spec.whatwg.org/multipage

* TODO link resources on alt text.

* https://htmhell.dev: Along with sinister abuses of HTML, this website shares development tips that will help ypu keep up-to-date with best practice.

* referenced
** Manuel Matuzović, [.cite]_Lost in Translation_, https://www.youtube.com/watch?v=Wno1IhEBTxc.
** https://www.matuzo.at/blog/2023/single-page-applications-criticism/
