
= Effective HTML
:chapter: 03
:url: ./effective-html/

WARNING: This chapter is a work in progress.

If you're here, you can probably write some HTML.
The web is the #1 hypermedia system after all, the one this book will spend the most time with,
and HTML is its format.

As with every aspect of the web, it has been exapted and reinterpreted by web developers in myriad ways.
Is it a document format?
Is it for applications?
Is it a rendering system?
Is it (gasp!) a programming language?
These are the contenders in the Eternal Debate of the web development world,
and none will ever win because none of them are right.

[quote, Roy Fielding, https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718]
____
When I say hypertext, I mean the simultaneous presentation of information and controls such that the information becomes the affordance through which the user (or automaton) obtains choices and selects actions.
____

HTML, like all hypermedia, blurs the distinction between the information being accessed and the application used to access it. HTML is for documents, insofar as you're willing to adopt a broad definition of "`document`" -- and it is for applications, ones that are interwoven with the data they process.

HTML is a hypermedium.

An HTML file is not a program that produces a human-readable document.
It _is_ the document.

Unfortunately, HTML isn't often discussed in its own right.
As a result, its development in terms of hypermedia controls has stagnated.

This chapter looks at HTML as something worth studying in its own right, even in this day and age.
It covers our best practices for writing/generating HTML,
and why HTML is something far cooler than a programming language.


== The state of affairs

Have you noticed that a lot of websites are bad?

 - Pages are bloated with `<div>` soup, and stylesheets are big as a result of trying to select elements in that mess. The result is slow loading times.footnote:[https://almanac.httparchive.org/en/2020/markup] Other than `<div>` being the most common element, the HTTP Archive Web Almanac found that 0.06% of pages surveyed in 2020 contained the nonexistent `<h7>` element. 0.0015% used `<h8>`.
 - So-called MVPs (minimum viable product) are released in open beta while being completely unusable by vast swathes of people -- UX not just buggy, but nonexistent.footnote:[https://adrianroselli.com/2022/11/accessibility-gaps-in-mvps.html] Is an inaccessible product "`viable`"?
 - Websites, including websites containing public data or results of publicly-funded research, are impossible to scrape programmatically.
 - Search engines have a hard time extracting useful information from a page, and rank that page lower as a result. 

In the rest of the chapter, we'll look at these issues in more detail and see how effective HTML can help us develop better websites.
However, we should first note that HTML is not a panacea.
If you care about machine readability, or human readability, or page weight, the most important thing to do is **testing**.
Test manually.
Test automatically.
Test with screenreaders, test with a keyboard, test on different browsers and hardware, run linters (while coding and/or in CI).

So where does HTML and the s-word come in?

Easy. Writing good, spec-compliant HTML lets browsers do a bunch of work for you. Furthermore, even when they don't, it makes it easier to write scripts that do. Fewer issues will be found during testing and you can release faster. When issues do come up, you can often fix them more easily by rewriting semantic HTML as opposed to heaping JavaScript and ARIA attributes over everything.

Good HTML will not absolve you from doing your job, but it will make it easier.


== `<div>` soup

While programming code is described as spaghetti when it's not well organized,
the food of choice for messy markup is soupfootnote:[hence BeautifulSoup, the web scraping library.].

HTML can turn into soup in a variety of ways,
usually due to a disregard for or misunderstanding of semantics
or due to an excess of layers between the developer and the HTML.

The best-known kind of messy HTML is `<div>` soup.
When developers fall back on the generic `<div>` and `<span>` elements instead of more meaningful tags,
we either degrade the quality of our websites or create more work for ourselves -- probably both.
For example, instead of adding a button using the dedicated `<button>` element,
a `<div>` element might have a `click` event listener added to it.
The developer would then (if they want to preserve the usability of their website) need to:

* Make the div keyboard-focusable, using `tabindex="1"`
* Expose it to assistive technologies as a button with `role="button"`

Of course, these are both easy fixes, but why bother?
Even if you always remember to add the correct attributes and JavaScript
(and yes, if you're making anything bigger than a button with a div, you will need JavaScript),
you've made your HTML less readable for little reason.
The source code of pages with div soup is difficult to edit and debug.

Furthermore, we often _don't_ remember these types of UX and accessibility issues.
**F5-Driven Development** is the way most of us write HTML:
write something, _Alt-Tab_ to the browser to see if it works, and go back to edit.
It's a fast and enjoyable way to build things,
but it means that during most of development,
developers are biased towards their own UI needs,
and users (who might use websites differently) become an afterthought.
However, if we use HTML, we can catch many of these issues before they ever occur, even before testing.

Given all this, why are so many developers writing div soup?
There is a tendency to understate the sophistication of HTML.

Instead, learn the meaning of every tag and consider each another tool in your tool chest.
(With the 113 elements currently defined in the spec, it's more of a tool shed).


=== Markdown soup

Markdown soup is the lesser known sibling of `<div>` soup.
This is the result of web developers limiting themselves to the set of elements that the Markdown language provides shorthand for,
even when these elements are incorrect.
Consider the following example of an IEEE-style citation:

[source,markdown]
----
[1] C.H. Gross, A. Stepinski, and D. Akşimşek, <1>
_Hypermedia Systems_, <2>
Bozeman, MT, USA: Big Sky Software.
Available: <https://hypermedia.systems/>
----
<1> The reference number is written in brackets.
<2> Underscores around the book title creates an <em> element.

Here, <em> is used because it's the only Markdown element that is presented in italics by default.
This indicates that the book title is being stressed, but the purpose is to mark it as the title of a work.
HTML has the `<cite>` element that's intended for this exact purpose.

Furthermore, even though this is a numbered list perfect for the `<ol>` element, which Markdown supports, plain text is used for the reference numbers instead.
Why could this be?
The IEEE citation style requires that these numbers are presented in square brackets.
This could be achieved on an `<ol>` with CSS,
but Markdown doesn't have a way to add a class to elements meaning the square brackets would apply to all ordered lists.footnote:[
We call `<ol>` and `<ul>` "ordered" and "unordered" lists. Both are actually ordered, however, and the difference is whether the place of a particular element is significant. For instance, instructions should usually be marked up with `<ol>` since it may contain references like "Repeat steps 3 to 5". If we were using a style like APA in our reference list, where citations are not referenced by number, we would use an <ul>.]

Don't shy away from using embedded HTML in Markdown.
For larger sites, also consider Markdown extensions.

[source,markdown]
----
{.ieee-reference-list} <1>
1. C.H. Gross, A. Stepinski, and D. Akşimşek, <2>
   <cite>Hypermedia Systems</cite>, <3>
   Bozeman, MT, USA: Big Sky Software.
   Available: <https://hypermedia.systems/>
----
<1> Many Markdown dialects let us add ids, classes and attributes using curly braces.
<2> We can now use the <ol> element.
<3> We use `<cite>` to mark the title of the work being cited (not the whole citation!)

You can also use custom processors to produce extra-detailed HTML instead of writing it by hand:

[source,markdown]
----
{% reference_list %} <1>
[hypers2023]: <2>
C.H. Gross, A. Stepinski, and D. Akşimşek, _Hypermedia Systems_,
Bozeman, MT, USA: Big Sky Software, 2023.
Available: <https://hypermedia.systems/>
{% end %}
----
<1> `reference_list` is a macro that will transform the plain text to semantic HTML.
<2> A processor can also resolve identifiers, so we don't have to manually keep the reference list in order and the in-text citations in sync.


=== Remedy: Stay close to the output

[quote, Manuel Matuzović, 'https://www.matuzo.at/blog/2023/single-page-applications-criticism[Why I\'m not the biggest fan of Single Page Applications]']
The fact that the HTML document is something that you barely touch, because everything you need in there will be injected via JavaScript, puts the document and the page structure out of focus.

Web frameworks, particularly SPA frameworksfootnote:[
This also applies to frameworks like Next and Remix that use SPA technologies like React to render static HTML.],
can have a tall tower of abstraction between the code the developer writes and the generated markup.
While these abstractions can allow developers to create richer UI or work faster,
their pervasiveness means that they can lose sight of the actual HTML (and JavaScript) being sent to clients.
Without diligent testing, this leads to poor semantics, inaccessibility, and bloat.

For example, a popular concept found in many frameworks is *components*.
Components encapsulate a section of a page along with its dynamic behavior.
While encapsulating behavior is a good way to organize code,
they also separate elements from their surrounding context,
which can lead to wrong or inadequate semantics,
and conceal the number of elements within.
The result is **component soup**, where information is hidden in component state rather than being present in the HTML.
In our Client Side Scripting chapter, we'll look at alternatives to component-based frameworks that can be used to avoid these shortcomings.

We should clarify that components, when used for the right purpose, can improve HTML clarity.
A good rule of thumb is to ask:
"`Could this reasonably be a built-in HTML element?`"
For example, a code editor is a good candidate,
since HTML already has `<textarea>` and `contenteditable` elements,
and since a fully-featured code editor will likely have many inner elements that don't provide much information to a reader.
By encapsulating these in a component, we are _extending_ HTML for our purposes,
rather than _abstracting_ it away.


== HTML5 soup

A set of elements introduced with HTML5 have become a symbol of semantic markup:

 - section
 - article
 - nav
 - header
 - footer

HTML5 soup happens when a developer comes to believe that
the more of these elements there are, the more semantic it is.
The results might look somewhat like this:

.HTMHell, [.cite]##10 <section> is no replacement for <div>#, https://www.htmhell.dev/10-section-is-no-replacement-for-div/
[source,html]
----
<section id="page-top">
  <section data-section-id="page-top" style="display: none;"></section>
</section>
<main>
  <section id="main-content">
    <header id="main-header">
      <h1>...</h1>
      <section class="container-fluid">
        <section class="row">
          <article class="content col-sm-12">
            <section class="content-inner">
              <div class="content__body">
                <article class="slider">
                  <section class="slide"> … </section>
                </article>
              </div>
            </section>
          </article>
        </section>
      </section>
    </header>
  </section>
</main>
----

If you're experiencing HTML5 soup, there are two remedies:
* Make sure you're using the meanings of elements defined in the spec.
  Don't try to use advanced HTML without having learned it.
* Don't try to be specific with your semantics when you can't or don't need to.
  Sometimes, `<div>` really is fine.


=== Remedy: Refer frequently to the spec

[quote,Confucius]
The beginning of wisdom is to call things by their right names.

The best resource for learning about HTML is the HTML specification.
The current specification lives on link:https://html.spec.whatwg.org/multipage[].footnote:[
The single-page version is too slow to load and render on most computers.]

Section 4 features a list of all tags in HTML.
It includes what tags mean, where they can occur, and what they are allowed to contain.
It even tells you when you're allowed to leave out closing tags!

[source,html]
----
<!doctype html>
This is a valid HTML document.
----

This chapter in particular is not only a great piece of reference material, but also a good read in general.
Reading it through (skipping over the implementation details) will give you a sense of how HTML is intended to be written.

.You get what you pay for
****
The close relationship between the content and the markup means that good HTML is actually quite expensive.
Most sites have a separation between the authors, who are rarely familiar with HTML and _very_ rarely want to think about it,
and the developers, who need to develop a generic system able to handle any content that's thrown at it --
this separation usually taking the form of a CMS.
As a result, having markup tailored to content, which is often necessary for advanced HTML, is rarely feasible.
Furthermore, for internationalized sites, content in different languages being injected into the same elements can degrade markup quality as stylistic conventions differ between languages.
Dishearteningly, but understandably, it's an expense few organizations can spare.

Thus, we don't demand that every site contains the "most semantic" HTML.
What's most important is to avoid _wrong_ HTML -- it can be better to fall back on a more generic element than to be precisely incorrect.
Most of the defects caused by _inadequate_ HTML can be caught through testing.

If you have the resources, however, putting more care in your HTML will produce a more polished site.
Much like style guides, well-written semantic HTML gives an air of quality and prestige to a document, even when few people notice it.
It can also make your HTML easier to maintain.
****


== The S word

[quote, _Mean Girls_ (2004)]
Gretchen, stop trying to make fetch happen! It's not going to happen!

In natural language, a word can only have a certain meaning if some group of people know it to have that meaning.
Whereas in programming, we are used to defining functions and variables, creating names for them at a break-neck pace.
This is possible because the computer doesn't need to understand the names of functions to execute them.
However, hypermedia formats are not programming languages.
The names in HTML are not _identifiers_ for behavior, but _words_ with well-understood meanings.
Any hypermedia format which lets documents define their own elements is an infinite universe of "`fetch`"-es to make happen.

This was a massive blind spot in the Semantic Web, which dominated hypermedia discourse for years:
its semantics attempted to replace natural language.

The semantic web is considered a failure, and Schematamania will soon be over.
Instead, when we talk about semantics, we refer to the simple act of using elements in accordance with their agreed-upon meaning.
Our semantics do

Instead of being extensible through schemas or namespaces, or whatever DTDs are, HTML is extended in two ways:

 - **Ad-hoc extensibility.** HTML is a fault-tolerant language, choosing to ignore things it doesn't recognize instead of throwing errors.
   This means you can use unspecified attributes.
   htmx relies on this heavily.
   If extensions see common acceptance, they might even be incorporated into specifications! (We can dream.)
 - **Specified extension points.** Things like classes, `<meta>` tags, custom elements and `data-` attributes are made for custom data.
   They can be used to build meta-languages embedded in HTML.

This might seem like a downgrade, and an anxiety-inducing one at that.
Think of the name collisions!
Indeed, it has some significant compromises, but it also correctly acknowledges that defining custom semantics without prior agreement between all parties is a fiction.
A flexible format -- not an infinity of namespaces with URLs pointing to nothing -- is "`software design on the scale of decades`".

Let's be real, after all -- out of all the sites using "`Open Graph`" tags, how many use the appropriate `prefix` attribute? How many of their developers even know the `prefix` attribute exists?


== The A word

The purpose of writing good HTML is not to please the specification deities.
It's to make good websites.
The spec is a good starting point when deciding how to mark something up,
but when implementations don't conform,
don't throw up your hands because you did what was specified.

It is of course frustrating when browsers and other tools misbehave.
It helps with the frustration is to recognize that hypermedia exchanges are not machine-to-machine communication.
An HTML file is not a program that produces a human-readable document.
It _is_ the document.
So, instead of banging your head against a wall, focus on people, not the tools they use.

Don't write HTML for browsers. or assistive tools, or validators.
HTML is not _for_ them.
HTML is for humans.


=== ARIA is easy -- as long as you stick to the basics

// Stick to the patterns

// Don't compromise UX just to avoid JS

// Consider using off the shelf components

// WAI has a very friendly webpage


=== Machine-readable HTML

==== Data attributes

// TODO to mark elements,to store state


==== Microformats

[source,html]
----
<ol class="reference-list">
  <li id="h-cite cite-hypers2023">
    <span class="p-author">C.&#8202;H. Gross</span>,
    <span class="p-author">A. Stepinski</span>,
    and <span class="p-author">D. Aksimsek</span>,
    <cite>Hypermedia Systems</cite>,
    <span class="p-publisher h-card">
      <span class="p-adr h-adr">
        <span class="p-locality">Bozeman</span>,
        <span class="p-region">MT</span>,
        <span class="p-country-name">USA</span>
      </span>:
      <span class="p-name">Big Sky Software</span>
    </span>,
    <time class="dt-published">2023</time>.
    Available:
    <a class="u-url" href="https://hypermedia.systems/">
      https://hypermedia.systems/
    </a>
  </li>
</ol>
----

<https://microformats.org/>


=== Custom elements

// TODO get on a soapbox about custom elements, why they're good and disappointing


== Relearning HTML

* HTML specification: https://html.spec.whatwg.org/multipage
* TODO link resources on alt text.
* https://htmhell.dev
* 
referenced
* Manuel Matuzović. _Lost in Translation_. https://www.youtube.com/watch?v=Wno1IhEBTxc
* https://www.matuzo.at/blog/2023/single-page-applications-criticism/