
= Effective HTML
:chapter: 03
:url: ./effective-html/


If you're here, you can probably write some HTML.
The web is _the_ hypermedia system after all, the one this book will spend the most time with,
and HTML is its format.

As with every aspect of the web, it has been exapted and reinterpreted by web developers in myriad ways.
Is it a document format?
Is it for applications?
Is it a rendering system?
Is it (gasp!) a programming language?
These are the contenders in the Eternal Debate of the web development world,
and none will ever win because none of them are right.

[quote, Roy Fielding, https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718]
____
When I say hypertext, I mean the simultaneous presentation of information and controls such that the information becomes the affordance through which the user (or automaton) obtains choices and selects actions.
____

HTML, as well as hypermedia before and after it, removes the distinction between the information being accessed and the application used to access it. HTML is for documents, insofar as you're willing to adopt a broad definition of "`document`", and it is for applications, ones that are interwoven with the data they process.

HTML is a hypermedium.

In this chapter, we'll learn about some HTML practices that are either skipped over,
or shoved in people's faces as _semantic_ or _accessible_ without understanding why.
We'll learn why HTML is far cooler than a programming language.


== Why relearn HTML?


Have you noticed that a lot of websites are bad?

 - Pages are bloated with `<div>` soup, and stylesheets are big as a result of trying to select elements in that mess. The result is slow loading times. footnote:[https://almanac.httparchive.org/en/2020/markup[]. Other than `<div>` being the most common element, the HTTP Archive Web Almanac found that 0.06% of pages surveyed in 2020 contained the nonexistent `<h7>` element. 0.0015% for `<h8>`.]
 - Websites, including websites containing public data or results of publicly-funded research, are impossible to scrape programmatically.
 - So-called MVPs (minimum viable product) are released in open beta while being completely unusable by vast swathes of people -- UX not just buggy, but nonexistent footnote:[https://adrianroselli.com/2022/11/accessibility-gaps-in-mvps.html]. Is an inaccessible product "`viable`"?
 - Search engines have a hard time extracting useful information from a page, and rank that page lower as a result. 

There are several disparate reasons for these issues, but the neglect of HTML is a significant one.

The way most of us write HTML (and likely the way many of us learned it) is a very tight feedback loop:
we write something, _Alt-Tab_ to the browser to see if it works, and go back to edit.
It's an amazingly fast and enjoyable way to build, but the way it's often practiced has a significant flaw:
_If it looks right, it gets shipped._
The developer is focusing almost exclusively to their own UI needs.
Any other way of using a website becomes an afterthought.

Thus, if you care about machine readability, or human readability, or page weight, what you should do is **test**.

Did you think I was going to talk about semantic HTML? Keep reading for that, but alas, it's no substitute for testing. Test manually. Test automatically. Test with screenreaders, test with a keyboard, test on different browsers and hardware, run linters (while coding and/or in CI). Read the markup -- the markup being sent to browsers, not the templates and code you write. Know exactiy what any type of hypermedia client is doing in any circumstance.

So where does HTML and the s-word come in?

Easy. Writing good, spec-compliant HTML lets browsers do a bunch of work for you. Furthermore, even when they don't, it makes it easier to write scripts that do. Fewer issues will be found during testing and you can release faster. When issues do come up, you can often fix them more easily by rewritlng semantic HTML as opposed to heaping JavaScript and ARIA attributes over everything.

Good HTML will not absolve you from doing your job, but it will make it easier.


== The S word

[quote,_Mean Girls_ (2004)]
____
Gretchen, stop trying to make fetch happen! It's not going to happen!
____

In human language, a word can only have a certain meaning if some group of people know it to have that meaning.
You could define your own words and use them, the aforementioned Ted Nelson and company really liked to, but it's difficult.
Providing a definition when you use it is not enough;
you also need an audience interested enough to read and remember that definition.

As this applies to computer languages too, any hypermedia format which lets documents define their own elements is an infinite universe of "`fetch`"-es to make happen.
Thus, let us renounce the schematamania that plagues many hypermedia discussions.
Instead, when we talk about semantics, we'll refer to about the simple act of using elements in accordance with their agreed-upon meaning.

Instead of being extensible through schemas or namespaces, or whatever DTDs are, HTML is extended in two ways:

 - **Ad-hoc extensibility.** HTML is a fault-tolerant language, choosing to ignore things it doesn't recognize instead of throwing errors.
   This means you can use unspecified attributes.
   htmx relies on this heavily.
   If extensions see common acceptance, they might even be incorporated into specifications! (We can dream.)
 - **Specified extension points.** Things like classes, `<meta>` tags, custom elements and `data-` attributes are made for custom data.
   They can be used to build meta-languages embedded in HTML.

This might seem like a downgrade, and an anxiety-inducing one at that.
Think of the name collisions!
Indeed, it has some significant compromises, but it also correctly acknowledges that defining custom semantics without prior agreement between all parties is a fiction.
A flexible format --not an infinity of namespaces with URLs pointing to nothing --is "`software design on the scale of decades`".

Let's be real, after all --out of all the sites using "`Open Graph`" tags, how many use the appropriate `prefix` attribute? How many of their developers even know the `prefix` attribute exists?


## Writing quality HTML

// TODO introduce the chapter

.Author's note
[.info]
****
This section is a collection of HTML best practices and footguns.
It's currently incomplete and **very** unorganized.
****


### HTML is for humans first

People who write HTML are referred to in Web platform specifications as "`authors`".
This sells our lot short by quite a lot, however;
from day to day, the average web developer might take on the role of
typesetter, copy editor, graphic designer, and of course, programmer.

... [TODO]

This is also important for non-visual usage.
Don't orient yourself solely towards following ARIA specifications or herding screen readers.
Those are the means, but usability is the goal.


### You don't need to guess what tags mean

[quote,Confucius]
The beginning of wisdom is to call things by their right names.

If you have ever made the mistake of publishing code online,
you might have had someone send you links to the HTML specification.
It was probably some section of chapter 4, "`The elements of HTML`".
(You might even have received it from this author).

While the big spec document with all the algorithms is probably better for smugly correcting people in chatrooms,
there is actually a developer-friendly version at https://html.spec.whatwg.org/dev/.
For a sufficiently patient reader, it's practically a textbook.

For a less patient reader, section 4 features a list of all tags in HTML.
It includes what tags mean, where they can occur, and what they are allowed to contain.
It even tells you when you're allowed to leave out closing tags!

[source,html]
----
<!doctype html>
This is a valid HTML document.
----


### Revisit the "`HTML5 elements`"

A set of elements introduced with HTML5 have become a sort of shorthand symbol for semantic markup:

 - section
 - article
 - nav
 - header
 - footer
 - TODO were there more

You can find websites that were clearly built with the mindset: "`The more of these elements there are, the more semantic it is.`" An example from the wonderful https://www.htmhell.dev/[HTMHell]:

.HTMHell, [.cite]##10 <section> is no replacement for <div>#, https://www.htmhell.dev/10-section-is-no-replacement-for-div/
[source,html]
----
<section id="page-top">
  <section data-section-id="page-top" style="display: none;"></section>
</section>
<main>
  <section id="main-content">
    <header id="main-header">
      <h1>...</h1>
      <section class="container-fluid">
        <section class="row">
          <article class="content col-sm-12">
            <section class="content-inner">
              <div class="content__body">
                <article class="slider">
                  <section class="slide"> … </section>
                </article>
              </div>
            </section>
          </article>
        </section>
      </section>
    </header>
  </section>
</main>
----


### Don't limit yourself to Markdown


////
### Hide stuff the right way

`hidden` attributex
- fully hidden from everyone
- might need to be normalized with CSS

`display: none` makes stuff disappear

"Visually hidden" utility
- seen by AT
- shows up in copy-paste
////


### Label your inputs, one way or another

`<input>` elements always need to be labelled. However, they don't necessarily need a visible `<label>` element. There are other ways to label:

// asciidoc why can't you be normal

- *Use a label, but hide it visually with CSS:* Use the visually hidden utility for this.

- *Use `aria-label`:*
+
.Search form using aria-label
[source,html]
----
<form>
  <input type="search" aria-label="Search for...">
  <button>Search</button>
</form>
----

- **Use `aria-labelledby`:**
This can be a good option for inputs where a nearby element provides context.
+
.Search form using aria-labelledby
[source,html]
----
<form>
  <input type="search" aria-labelledby="search-button">
  <button id="search-button">Search</button>
</form>
----


### Don't use <figcaption> for alt-text

Use the `alt` attribute instead! Figure captions shouldn't regurgitate the information in an image. Instead, they should be used to give context or provide metadata such as source or date. The `alt` attribute, on the other hand, should be a substitute for the image, describing the relevant aspects of what is depicted for the benefit of people who can't view it.

Captions might be misused for alt text when the author wants the alt text to be visible as text. To achieve this, some social media platforms use an "`ALT`" button that opens the alt text in a popup window. The main drawback of this approach is that you need to implement a popup window. You could also use a `<p>` after the image with `aria-hidden` on it.

.The `alt` attribute
****
They say a picture is worth a thousand words. How am I supposed to produce an acceptable substitute in just a few sentences?

When writing alt text, you should only provide the information that is relevant. This means that the alt text should not be stored with the image (as is unfortunately the case with many CMSs) but in the document --because different aspects of an image are relevant in different contexts.

TODO link resources on alt text.
****


### Write useful link text

Wherever possible, the text of a link should describe what the link points to without much context needed. Of course, you might need to alter it to fit a sentence structure, but you should avoid links that don't give information other than "`this is a link`".

|===
| Do | Don't

| For user records, [click here]
| [User records]
|===


### ARIA is easy --as long as you stick to the basics

// Stick to the patterns

// Don't compromise UX just to avoid JS

// Consider using off the shelf components

// WAI has a very friendly webpage


## Extending HTML

### Data attributes

// TODO to mark elements,to store state


### Microformats

<https://microformats.org/>


### Custom elements?

// TODO get on a soapbox about custom elements, why they're good and disappointing



