
= Effective HTML - Pullouts

WARNING: test of key ideas as pullouts to be sprinkled throughout the book
////
Many pieces of the chapter read like little gems; these might work well as pullouts.
Pieces have been moved to end of chapter "'html notes'" (or similar).
This is just an option to consider.

I we go this route, it would be useful to index or add a ToC entry for 'HTML Topics'

Note: I used [.design-note] to flag for formatting. 
which... may not be useful
//// 


// TODO: maybe an info gem?
[.design-note]
.On Lists 
****
We call `<ol>` and `<ul>` "ordered" and "unordered" lists. Both are actually ordered, however, and the difference is whether the place of a particular element is significant. For instance, instructions should usually be marked up with `<ol>` since it may contain references like "Repeat steps 3 to 5". If items in our list are not referenced by number, we would use an `<ul>`.
****



// TODO: Some readers may want more specific advice on how to write HTML for humans. 
.Screen Reader Rage
****
The spec is a good starting point when deciding how to mark something up,
but when browser implementations don't conform,
we shouldn't throw up our hands because we did what was specified.

After all, browser implementers do a _lot_ of work to deal with developers' broken HTML -- is it such a burden to return the favor?

It is frustrating when browsers and other tools misbehave.
Accessibility itself feels inaccessible sometimes.
To reduce the frustration it may help to recognize that hypermedia exchanges are not machine-to-machine communication.
An HTML file is not a program that produces a human-readable document.
It _is_ the document.
So, instead of banging your head against a wall, focus on people, not the tools they use.

Don't write HTML for browsers. or assistive tools, or validators.
HTML is not _for_ them.
HTML is for humans.
****


// maybe move to ch1? The Essence of HTML as a Hypermedia
.What is HTML?
****
[quote, Marshall McLuhan]
The medium is the message.

Is it a document format?
Is it for applications?
Is it a rendering system?
Is it (gasp!) a programming language?

[quote, Roy Fielding, https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718]
____
When I say hypertext, I mean the simultaneous presentation of information and controls such that the information becomes the affordance through which the user (or automaton) obtains choices and selects actions.
____

HTML, like all hypermedia, blurs the distinction between the information being accessed and the application used to access it. HTML is for documents, insofar as you're willing to adopt a broad definition of "`document`" -- and it is for applications, ones that are interwoven with the data they process.

HTML is a hypermedium.

An HTML file is not a program that produces a human-readable document.
It _is_ the document.
****


// TODO: keep? some readers will love it, others may wonder how it fits
format as pullout, like Web Components, ARIA
.The "`Semantic Web`"
****
[quote, '_Mean Girls_ (2004)']
Gretchen, stop trying to make fetch happen! It's not going to happen!

The "Semantic Web" was a vision of a system that could both express any kind of human knowledge, and be useful for computing.
It planned to achieve this using _ontologies_, repositories of schemas like "person", "movie" and "species" and relations like "named", "part of" and "created by".

The problem with this vision is that information on the Web rarely fits into neat categories.
Because no single ontology can be defined that encapsulates all kinds of information one might wish to publish on the Web,
Semantic Web systems need to be pluggable with different schemas.
In turn, a Semantic Web client, in order to do something useful with an arbitrary piece of HTML, needs to be able to parse these schemas, which means we need to define a standard machine-readable format for ontologies.
But a single format couldn't express every kind of object and relation...
It's turtles all the way down.

In practice, most implementations stop at the topmost turtle.
Ontologies are defined in natural language,
and clients are hardcoded to support a fixed set of schemas.
The requirement for prior agreement between server and client means this technology does not have the generality of the Web,
and for most use cases, you might as well define a JSON API.

_The Semantic Web has nothing to do with semantic HTML_.
****