= Foreword
:chapter: -1

// from @mamund:
// * not sure how to format this unit (metadata, etc.)
// * feel free to edit/delete as needed to fit your tastes
// * i left out links/refs in this draft. let me know if you'd like them included
// * 

While there have been many books on the topic of hypermedia, there is a select number of publications that chronicle important advances in the field of hypermedia and this book is one of them. Not only does this book describe the benefits of creating hypermedia-driven applications (HDAs), it leads the reader through working and practical examples of how to do just that. And, in doing so, the authors (Gross, Stepinski, and Akşimşek) call out contributions from important figures in the history of hypermedia systems. And, as of this writing, that history spans more than half a century.

In 1974, Ted Nelson's _“Computer Lib/Machine Dreams”_ marked the start of the modern hypermedia era with a book that Steven Levy (author of _“Hackers”_) described as "the epic of the computer revolution." Nelson is credited with coining the terms HyperText, HyperLink, HyperMedia, and HyperData as well as Intertwingluarity; the notion that all information is connected -- both intertwined and intermingled. Almost half a century ago, he foretold a future where any person could publish anything anytime without the need for permission from any central controlling source. And his hyperlinks were the engine of that future.

It took two decades before Nelson's idea of intertwingled computing became widespread. Along the way, Douglas Engelbart created the _oN-Line System_ or NLS, Wendy Hall built the _Microcosm_, and, eventually, in the 1980s, Tim Berners-Lee defined the World Wide Web (WWW), HTML, and HTTP. It was Berners-Lee's iteration that has become the backbone and the standard for the intertwingularity we all experience today. 

By the year 2000, the technical foundations of "the web" were documented in Roy Fielding's PhD dissertation (_“Architectural Styles and the Design of Network-based Software Architectures”_). In that work, Fielding defined the architectural model of _REpresentational State Transfer_ or REST. This set of system properties and implementation constraints have proven -- even a quarter-century later -- to be a reliable model for designing and building the intertwingled machines that today affect billions of people around the globe.

Even though Fielding's work was important, it wasn't until Leonard Richardson and Sam Ruby published _“RESTful Web Services”_ in 2008 that the REST model became well-known to the world of software architecture and development. Backed by the Ruby programming platform, the ideas behind Fielding's REST model became _de rigueur_ for the creation of web-based services and client applications.

One of the reasons Richardson and Ruby's work was so important was that, unlike dissertations and futuristic predictions, the _RESTful Web Services_ book outlined a practical working framework for building powerful applications for the Web. It described not only the power of REST but also provided step-by-step instructions on how to build them. Richard and Ruby brought together the hypermedia scholarship of the previous twenty years all in one place. 

And now we can add this book (_“Hypermedia Systems”_) to that list of important works. From the book's introduction through the step-by-step directions on how to use HTMX for browsers and Hyperview for mobile devices, the authors describe the benefits of creating hypermedia-driven applications (HDAs). They also offer dozens of practical working examples the reader can use right away in building their own hypermedia solutions. 

I've been working in the field of hypermedia for close to thirty years and have seen quite a few books, papers, dissertations, and programming platforms come and go in that time. Occasionally, one of these works "nails it" -- provides the right mix of theory and practice delivered in a way that helps readers make a connection between their own efforts and the activities of the community at large. I am happy to say that this book is one of those works. The authors have not only created powerful tooling in HTMX and Hyperview, they have also advanced the notion of hypermedia systems and hypermedia-driven applications in ways that a wide audience can understand and apply. 

Nelson describes a future where the barriers to publishing and data sharing are lowered and the creative energies of the world are easily shared and applied. This is neither a new nor unique idea but one that does need continual renewal and encouragement. Nelson saw his hyperlink and hypermedia as the driving force for intertwingularity between people and machines around the world. In this idea alone, hypermedia is a powerful approach to creating computer systems that enable people to work together for the common good. As this book's authors say, "Hypermedia was a great idea! It still is!"

_Mike Amundsen, April 2023_
